FROM nginx:latest

MAINTAINER caohui <772071248@qq.com>

COPY nginx.conf /etc/nginx/nginx.conf

COPY conf.d/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]

